### ISSUE TITLE
Handle the wrong configurations

### ISSUE THREAD

**Issue by Marius786** [presslabs/toplytics#103]
Handle the case when the JSON conf data are wrong and you try to connect to GA account. This will generate errors like this one:

`Dec 13 19:52:18 olarmariustk.instance olarmariustk:  PHP User Error:  Exception: 401 -> Error fetching OAuth2 access token, message: 'invalid_client' in /www/wp-content/plugins/toplytics/inc/class-toplytics-submenu-configure.php on line 114 when calling trigger_error(), request: GET /wp-admin/options-general.php?page=toplytics/toplytics.php&code=4/O7I7VkN8mkdKJuRZRhU3sTncZMoiHevPv-LznivgvKQ, request_id: 4abb380a046e30345519ae229ff29e4a`

**Comment by cristianuibar** [comment]
In V4 we have a validation method to make sure we have all the necessary data in the JSON to be able to attempt a GA connection.

If the config does not pass validation, it will instruct the user to try the Private Auth Method, because it's most probably an error on our side (we have remote config now with V4).
