### ISSUE TITLE
Check if Toplytics connection to GA is up-to-date

### ISSUE THREAD

**Issue by t-ionut** [PressLabs/toplytics#119]

**Comment by krodyrobi** [comment]
Check if the https://www.presslabs.com/help/toplytics/usage is up to date and the plugin help is as well.

**Comment by krodyrobi** [comment]
The config from the site is a little convoluted but for a non GA user I did just fine, both steps either from the plugin or from the site work. It may just be that the cron failed to refresh the token, or couldn't because they exceeded a limit or smth. When we get to clean plugins up then we will add logs for all edges..
