### ISSUE TITLE
Time zone

### ISSUE THREAD

**Issue by jimihenrik** [PressLabs/toplytics#77]
Heya. Just noticed that in the debug my clock was quite wrong so probably a time zone thing?

Fixed it for myself by adding `date_default_timezone_set(get_option('timezone_string'));` to the Toplytics function __construct.

Just giving heads up about that.

Also, in the version 2.x you seemed to force refresh the analytics by opening the settings page, this doesn't seem to be case anymore, correct? (It would be nice if there was a button for that too.)

**Comment by Marius786** [comment]
Howdy and thanks for your feedback. Please feel free to make pull requests, if you want, for every bug/issue/enhancement you find in Toplytics.

About the button for refresh the stats, I think this button is useful only on a preview page, where you can actually see the result of pushing this button. We will keep this in mind for the new versions. Thanks again.

**Comment by jimihenrik** [comment]
Heya indeed.

Yeah, I haven't really ever used github so I'm not really familiar with pull requests, and I'm not that good of a coder; so I just point things out and you as a professional can then implement the best you see fit :laughing:

Maybe I'll learn to do pull requests some day!

And yeah, I agree about the refresh button, it would just be nice for development.

**Comment by Marius786** [comment]
With Github interface it's easy to do a pull request. All you have to do, after you test the code on some WP site, you must go to the file, edit the change and then instead of save the changes you can only `Propose file change`. The Github will take care of making a fork for this project on your account and then make the pull request from this fork. The chenges will be on your fork until the pull request is accepted. I just want you to know that this code is open for every contribution :+1:

**Comment by jimihenrik** [comment]
Sure thing!

Just trying out the v3 on the dev site again. And then a medium sized production site. Last time I tried with bigger production site the shortcodes in my text widget slowed the site so much it didn't even load properly, have to see if it works on a little smaller traffic (~million hits last 30 days) site.

**Comment by Marius786** [comment]
This use case needs deep investigation. Thanks.

**Comment by Marius786** [comment]
Related to c093c5a27f4c67d23d446860f19273ce1381b8ca
