### ISSUE TITLE
Handle `Google APIs Client Library for PHP` generated conflicts.

### ISSUE THREAD

**Issue by Marius786** [presslabs/toplytics#90]
Find a way to detect and add notice about the other plugin that has a lower version of the Google APIs Client Library for PHP. This library, from other plugin, can generate conflicts. One plugin with conflict is Google Analyticator 6.4.7.3.

**Comment by mariusveltan** [comment]
One approach for avoiding this conflict for the Google APIs Client Library for PHP could be requiring the API files on a later hook - since most plugins generally require the lib files right away.
In my case, I solved such a conflict by requiring the library on admin_init, checking in advance that the respective classes were not already defined.
